name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: jar

    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name != 'pull_request' }}
      with:
        path: "build/libs/freenet-KeyUtils.jar"
        name: "freenet-keyutils"

